### ISSUE TITLE
Request: ability to set storySource link via pattern

### ISSUE THREAD

**Issue by quantizor** [Sirrine-Jonathan/storybook-source-link#1]
When linking to a source repository like GitHub, we can make use of pattern-based replacement since the files will follow a predictable structure. Would love to be able to do something like this at the `preview.js` level so annotation is not required on all child story suites:

```
parameters: {
    sourceLinkPrefix: `https://github.com/org/repo/blob/main/`,
},
```

Which would translate behind the scenes into `https://github.com/org/repo/blob/main/src/story.tsx` per story file for an example story file located at `src/story.tsx`.

**Comment by quantizor** [comment]
I initially tried doing this using `__filename`, but this resolves to `preview.js` which isn't useful. I figured as an addon you might have better access to storybook context to do this sort of replacement.

**Comment by Sirrine-Jonathan** [comment]
That sounds good to me. I initially thought of doing something like this using an entry in package.json that points to the repository. This seems more flexible though. I added some tags so someone can come in and work on this if they want. Otherwise I'll eventually get to it.

**Comment by Sirrine-Jonathan** [comment]
Wrote a [PR](https://github.com/Sirrine-Jonathan/storybook-source-link/pull/2) so I can revert easily if need be. The CI tests are messed up so I may just force merge it. I've wrote a bunch of unit tests with this PR.

**Comment by Sirrine-Jonathan** [comment]
The feature branch has officially been [merged](https://github.com/Sirrine-Jonathan/storybook-source-link/pull/2) into main and released on [npm](https://www.npmjs.com/package/storybook-source-link). Let me know if Anything doesn't work as expected. It should be good. I tested the crap out of it. But if anything comes up, feel free to open another issue.
