### ISSUE TITLE
source-link not compatible with latest version of Storybook 7 

### ISSUE THREAD

**Issue by oeem1011** [Sirrine-Jonathan/storybook-source-link#9]
Getting peer dependency conflicts with storybook7@latest. Is this addon getting updated?

**Comment by severinlandolt** [comment]
Hi @Sirrine-Jonathan, thank you for your community contributions to Storybook. I want to use your addon over at @tremorlabs, do you plan to make an update for storybook 7.0?

**Comment by Sirrine-Jonathan** [comment]
I do. I've been meaning to this week, actually.

**Comment by Sirrine-Jonathan** [comment]
Just want to update here I started work on this here on branch [sb-v7](https://github.com/Sirrine-Jonathan/storybook-source-link/tree/sb-v7). I quickly ran into an issue with how I have tests written not working for webpack 5.

I have a long weekend coming up where I'll carve out some more time.

Thanks for the patience!!

**Comment by Sirrine-Jonathan** [comment]
Alright. Took a bit, but I got it.
https://www.npmjs.com/package/storybook-source-link

I'm going to close this, but let me know if you have any issues moving forward. I tested it out just a moment ago and realized I'd missed a crucial step in the setup instructions that was pointed out in https://github.com/Sirrine-Jonathan/storybook-source-link/issues/8

**Comment by severinlandolt** [comment]
Thank you @Sirrine-Jonathan !
